apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana-operator
  annotations:
    argocd.argoproj.io/sync-wave: "11"
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: product-metrics
  source:
    path: manifests/infrastructure/grafana-operator/base
    repoURL: https://github.com/PixelJonas/metrics-demo-infra
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
