apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

commonAnnotations:
  argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true

bases:
  - https://github.com/redhat-canada-gitops/catalog/grafana-operator/overlays/aggregate?ref=grafana
