apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: product-metrics-infra

commonAnnotations:
  argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true

bases:
  - namespace.yaml
  - https://github.com/redhat-canada-gitops/catalog/grafana-operator/overlays/aggregate?ref=grafana

patchesJson6902:
  - target:
      version: v1
      group: rbac.authorization.k8s.io
      kind: ClusterRoleBinding
      name: grafana-proxy
    path: patch-proxy-namespace.yaml
  - target:
      version: v1alpha1
      group: operators.coreos.com
      kind: Subscription
      name: grafana
    path: patch-grafana-version.yaml
